const DEFAULT_WORDS_COUNT = 200;
const COUNT_DOWN_90 = 90;
const COUNT_DOWN_60 = 60;
const COUNT_DOWN_30 = 30;
const COUNT_DOWN_15 = 15;
const DEFAULT_COUNT_DOWN = COUNT_DOWN_60;
const RESTART_BUTTON_TOOLTIP_TITLE = "Press [Tab] + [Enter] for next set of words";
const REDO_BUTTON_TOOLTIP_TITLE = "[Tab] + [Space] to type the same set of words";
const ENGLISH_MODE_TOOLTIP_TITLE = "English Mode";
const ENGLISH_MODE = "ENGLISH_MODE";
const C_MODE = "C_MODE";
const CPP_MODE = "CPP_MODE";
const JAVA_MODE = "JAVA_MODE";
const PYTHON_MODE = "PYTHON_MODE";
const GAME_MODE = "GAME_MODE";
const GAME_MODE_DEFAULT = "WORD_MODE";
const WORD_MODE_LABEL = "word";
const PACING_CARET = "caret";
const PACING_PULSE = "pulse";
const smoothCaret = "smooth-caret";



export {
  DEFAULT_WORDS_COUNT,
  DEFAULT_COUNT_DOWN,
  COUNT_DOWN_60,
  COUNT_DOWN_30,
  COUNT_DOWN_15,
  COUNT_DOWN_90,
  ENGLISH_MODE,
  C_MODE,
  CPP_MODE,
  JAVA_MODE,
  PYTHON_MODE,
  RESTART_BUTTON_TOOLTIP_TITLE,
  REDO_BUTTON_TOOLTIP_TITLE,
  ENGLISH_MODE_TOOLTIP_TITLE,
  GAME_MODE,
  GAME_MODE_DEFAULT,
  WORD_MODE_LABEL,
  PACING_CARET,
  PACING_PULSE,
  smoothCaret,
};
